name			    = "Enhanced First Aid Kits";					            // Name of your mod
author			    = "Miss Heda";				                                // Affects Arma 3 Launcher, when the mod are loaded as local
logo			    = "logo.paa";			                                    // Logo displayed in the main menu
logoOver		    = "logo.paa";	                                            // When the mouse is over, in the main menu
tooltip			    = "";
tooltipOwned	    = "";				                                        // Tool tip displayed when the mouse is left over, in the main menu
picture			    = "logo.paa";		                                        // Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName		    = "Support Discord";
action			    = "https://discord.gg/Jud6gyzFYx";			                // Website URL, that can be accessed from the expansions menu
overview		    = "Enhanced First Aid Kits by Miss Heda";                   // Supports structured text
hideName		    = 0;						                                // Hide the extension name
hidePicture		    = 0;						                                // Hide the extension menu
dlcColor[]		    = { 0.23, 0.39, 0.30, 1 };	                                // Color used for DLC stripes and backgrounds (RGBA)
logoSmall		    = "logo.paa";		                                        // Display in creative lists, next to the entities added by the mod