// Generated by tools/build_acme_overrides.py - do not edit by hand.
//
// ACM Extended reads and takes the medic's supplies itself instead of asking ACE medical: it counts
// with ace_common_fnc_getCountOfItem and ace_common_fnc_uniqueItems and takes with the engine's
// removeItem. Nothing of that sees into a kit.
//
// - The two ACE functions are redefined with ACE's own code plus the unit's kits (overrides\).
// - ACM's portable oxygen opens a tank out of a kit when none is loose, and the refill at a
//   medical vehicle takes the empty tank out of a kit (overrides\).
// - Every function of ACM Extended that takes an item with removeItem is redefined with the same
//   code, the removeItem replaced by efak_medical_fnc_takeItem (acme\).
//
// The function library takes the last definition it sees, and this addon loads after ACE and ACM
// Extended. ACE and ACM compile final, so a runtime reassignment would be refused.
class CfgFunctions {
    class EFAK_overwrite_common {
        tag = "ace_common";

        class ace_common {
            class getCountOfItem {
                file = QPATHTOF(legacy\overrides\fnc_getCountOfItem.sqf);
            };
            class uniqueItems {
                file = QPATHTOF(legacy\overrides\fnc_uniqueItems.sqf);
            };
        };
    };

    class EFAK_overwrite_ACME {
        tag = "ACME";

        class infusion {
            file = QPATHTOF(legacy\acme);
            class ccApply {};
            class chestSealOpen {};
            class chestSealRequest {};
            class epinephrineDrawCardiac {};
            class epinephrinePrepare {};
            class givePreparedBag {};
            class hpmkPrep {};
            class ivMinigameRegister {};
            class laryngoPassTube {};
            class medicationTakeSources {};
            class nrbApply {};
            class place18g {};
            class salineFlush {};
            class suctionBulb {};
            class thoraMouseDown {};
            class transfusionSpikeOrAdd {};
            class transfusionYTubing {};
            class ventInventoryLocal {};
            class vialTake {};
        };
    };

    class EFAK_overwrite_ACM_circulation {
        tag = "ACM_circulation";

        class ACM_circulation {
            file = QPATHTOF(legacy\acme);
            class Syringe_PrepareFinish {};
            class TransfusionMenu_AddBag {};
            class canConnectAED {};
        };
    };

    class EFAK_overwrite_ACM_breathing {
        tag = "ACM_breathing";

        class ACM_breathing {
            class refillOxygenTank {
                file = QPATHTOF(legacy\overrides\fnc_refillOxygenTank.sqf);
            };
            class useOxygenTankReserve {
                file = QPATHTOF(legacy\overrides\fnc_useOxygenTankReserve.sqf);
            };
        };
    };
};
