#!/usr/bin/env python3
"""Generate the pool of unique kit instance classes.

Every kit in EFAK 2.0 needs its own identity so it can carry its own contents.
Arma has no per-item variables, so - like TFAR does for its radios - each kit
type ships one "prototype" class plus a pool of concrete classes that inherit
from it. A prototype picked up by a player is swapped for a free concrete
class, and the contents are stored against that classname.

Instances keep scopeArsenal = 2 (inherited) but set ace_arsenal_hide, so ACE
Arsenal never lists them yet still preserves them as "unique items" in a
loadout instead of silently dropping them.

Usage:  python tools/generate_instances.py
"""

import io
import os

# Keep in sync with EFAK_INSTANCES_PER_KIT in addons/core/script_component.hpp
INSTANCES_PER_KIT = 400

KITS = ["efak_IFAK", "efak_AFAK", "efak_MFAK"]

HEADER = """// AUTO-GENERATED by tools/generate_instances.py - do not edit by hand.
// One concrete class per kit instance, see the script for the why.
"""

TEMPLATE = (
    'class {kit}_{i}: {kit} {{'
    'ace_arsenal_hide = 1; ace_arsenal_uniqueBase = "{kit}"; '
    'EFAK_prototype = 0; EFAK_instanceId = {i};'
    '}};'
)

OUT = os.path.join(os.path.dirname(__file__), "..", "addons", "core", "CfgWeapons_instances.hpp")


def main():
    lines = [HEADER]
    for kit in KITS:
        lines.append("// %s instances" % kit)
        for i in range(1, INSTANCES_PER_KIT + 1):
            lines.append(TEMPLATE.format(kit=kit, i=i))
        lines.append("")
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %s (%d classes)" % (os.path.normpath(OUT), len(KITS) * INSTANCES_PER_KIT))


if __name__ == "__main__":
    main()
