#include "script_component.hpp"

// Loads only when ACM Extended is there: an addon whose required addons are missing is skipped,
// quietly. ACM Extended brings ACM with it, so the ACM compat is loaded as well - and this one after
// it, so its kit contents are the ones that count.
//
// An ACM Extended with ACME_fnc_itemCount reads and takes supplies through ACME_fnc_itemCount,
// itemTake and itemList, which ask EFAK's public API itself - nothing to do here but the kit contents.
// An older one reads the inventory directly and sees nothing in a kit: it gets EFAK's legacy overrides
// (legacy\, generated by tools/build_acme_overrides.py) - copies of its own functions that take out of
// a kit. Which one is loaded is only known when the game starts, so this config is not binarized and
// the game itself answers __has_include, the way ACE's optional patches do it.
#pragma hemtt flag pe23_ignore_has_include
#if __has_include("\acm_extended\functions\fn_itemCount.sqf")
#else
#define EFAK_LEGACY_ACME
#endif

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "efak_compat_acm",
            "efak_medical",
            "ACM_core",
            "ACM_Extended"
        };
        skipWhenMissingDependencies = 1;
        author = "Miss Heda";
        url = ECSTRING(main,URL);
        VERSION_CONFIG;
    };
};

#include "CfgEFAKKits.hpp"

#ifdef EFAK_LEGACY_ACME
#include "legacy\CfgFunctions.hpp"
#include "legacy\CfgTreatmentActions.hpp"
#endif
